### ISSUE TITLE
Add/refine weapon mechanics

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#48]
- More weapons
- More effects
- Refine the relationship between moving and shooting

**Comment by 7yl4r** [comment]
I accidentally broke bullet movement yesterday, so bullets just dropped and sat until ca came up to them, effectively working like a "bomb"... and it was actually pretty fun. I guess we should add in some different weapon types? Perhaps as "powerups" or something of that nature?

**Comment by 7yl4r** [comment]
I'm sure we've all got ideas for more weapons, but since this thread isn't getting us anywhere I'm closing it down. Please do open new issue for specific suggested weapon types though.

**Comment by 7yl4r** [comment]
On second thought, here's my list of weapon types for arcade mode:

a. sniper-style weapon : slow fire rate, quick bullet speed, large impact, 0 bullet spread
b. machine-gun style : fast fire rate, mediums bullet speed, small impact, large bullet spread
c. bomb-style : med fire rate, 0 speed, medium impact, limited bullet lifespan(?)
d. grenade-launch style : med-slow rate, med-slow speed, detonation triggered by keypress (not impact), detonation clears large area

(a) is nearest to what we have currently. (d) could also be useful for _adding_ vyroids to the scene, which is something I'd like to play with in the genetic lab.

Options for implementing in arcade-mode:
1. as powerups: one of the above is the default, others are temporary powerups
2. as character-customization: choose one weapon type at beginning of game
3. weapon-switching: allow player to switch weapons at will, or use multiple types via different keys

3 will be difficult to do on mobile though.

Ideas on how we can improve on this plan?

**Comment by BrianErikson** [comment]
I definitely think, for arcade mode, that the powerups are the best way to implement it.

**Comment by 7yl4r** [comment]
Okay, so here's my plan:

Players have a base configuration which they can set up on a orb configuration screen in the menu.
Powerups come in on top of the base config. 

For now, with the focus on the arcade version, there will be 1 default weapon (more later) and the powerups will be my first focus. Now, given the weapon types as above:

a. sniper
b. machine-gun
c. bomb
d. grenade-launch
e. default/pistol (new to this list) - medium-low everything

What should the powerups be so that they are beneficial regardless of the weapon being used?
1. fire-rate++
2. detonation-size++
3. bullet-speed++ (no effect for bomb?)
4. bullet-size++ (no effect for grenade-launch?)
5. bullet-accuracy (only really matters for machine-gun)

any other powerup ideas?

**Comment by BrianErikson** [comment]
Ported over to trello
