### ISSUE TITLE
wind

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#51]
We've got a lot going on visually, but after [some discussion](https://www.reddit.com/r/worldbuilding/comments/3jqx1c/2d_worldbuilders_unite/) on the practicalities of our game-world, it seems to me that wind is going to be very important to the inhabitants/plants (namely to move nutrients around). Therefore I think I'd like to include some aesthetic wind effect. So here's my questions:
1. what should this look like? 
2. how should we "code" this?
3. should we try to work this into gameplay?

my initial thoughts:

2: map has a (large) grid, and in each square we can define wind direction and intensity

3: wind could push projectile movement

**Comment by 7yl4r** [comment]
All I can think of for (1) is something like [this](https://www.windyty.com/?pressure)

**Comment by BrianErikson** [comment]
Something like [this](http://www.ibiblio.org/e-notes/webgl/gpu/fluid.htm) might be useful. Instead of two colored flows, you could have one transparent flow and one colored one for the wind. The issue with this idea would be that it is nearly impossible to weave gameplay into it since it's a GPU effect.

The easiest way to do this I think would be to represent the wind by the result of the effect. In this case you'd see nutrients moving in certain directions. 

I think that wind might take a bit of effort to achieve right, so it probably needs to be integral to gameplay at least

**Comment by 7yl4r** [comment]
@BrianErikson , that looks pretty fancy. The trouble with doing it on the gpu is that we can't interact with objects (buildings) like wind should... right?

**Comment by BrianErikson** [comment]
@7yl4r, correct.

**Comment by 7yl4r** [comment]
Could we... use pixels marked with a particular color value as collider-pixels or repulsor-pixels which push the particle away? 

I think I really need to dig into how particle effects and shaders work; it seems to be a persistent pain point for me.

**Comment by 7yl4r** [comment]
current PoC state: 

https://youtu.be/1vS8FNo4L4g

it's definitely not perfect. Still needs quite a bit of work before getting merged in.

**Comment by BrianErikson** [comment]
ported over to trello
