### ISSUE TITLE
memory usage monitor on profiler inaccurate

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#52]
We need to use some other method to gauge memory usage, as I just introduced a major memory leak and watched the profiler label go unchanged until the app crashed with out-of-memory-err.

**Comment by BrianErikson** [comment]
`(Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory())/1024` seems to be what we want. See if that works for you

**Comment by 7yl4r** [comment]
I'm not sure if this is fixed or not. In arcade mode it seems to climb steadily and then suddenly drop down. In contrast, my system resource monitor shows stable memory usage.

**Comment by BrianErikson** [comment]
It appears that in the OS, the memory usage displayed is the memory usage allotted for the JVM. The one that you see that is fluctuating in the game is the amount used out of the amount allotted for the JVM. When you see the allotted memory increase in the OS, that's because the JVM hit the max amount of memory allotted, and expanded it's claim.

Verified that this is working correctly with a JVM profiler
