### ISSUE TITLE
Collider "jerk" and wall tunneling

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#69]
Especially noticeable when bumping into other characters, however I was also able to push through some of the thinner walls by wedging into corners.

**Comment by BrianErikson** [comment]
I haven't been able to reproduce pushing through walls lately, but interacting with small objects has always been an issue. When interacting with the NPC, `Dyn4j` reports a penetration depth of `> 0.5`, whereas the thicker walls usually reports a penetration depth of `< 0.3`. Haven't found a non-hacky fix for this yet.

**Comment by BrianErikson** [comment]
Right now, the physics system is kind of being treated as a sensor system, and the `MovementComponent` just forces it to where it needs to be. I think a good way to solve this is to abstract away the `MovementComponent` into two discreet classes; one for the objects without a collider, and one for objects that do have one, so that the physics system can handle collisions more effectively. 

Either way, I think some major (necessary) refactoring needs to be done to solve this. I'll see what I can come up with.

**Comment by 7yl4r** [comment]
Maybe just dampening the push being applied to the movement component could work? Since we don't really have things pushing each other around, we might get away with just cancelling out movement which would put an object into another one.

**Comment by BrianErikson** [comment]
This was fixed with the merge of the artemis branch -- we are now using Box2D for physics
