### ISSUE TITLE
Asynchronous CA Generation

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#77]
I've been mulling this over for a while, and I think we might be able to pull this off by:
- Recording which CA gets destroyed by the player
- Maintaining a game `CA grid state` separately which gets displayed
- Appending the sectors destroyed by the player during the last update to the newly generated state

This would have the side-effect of the player not being able to instantaneous change the pattern in which the CA generates, as it would always be a generation behind. However, the visuals of a bullet destroying a sector instantly would still be preserved. 

This method has it's drawbacks but the trade-off might be worth it if we want to get more complex with our generation rules.

**Comment by 7yl4r** [comment]
I did push CA generation computations into their own thread in 0717bbac98075aa5668c02977d70560d134ac4b0, but I had to dial them back from running continuously (to ~<50% cpu usage b96bd629cf98aef68807947caa9e73aeaae9bbdf) because my laptop was borderline overheating. =P

**Comment by 7yl4r** [comment]
I think that we're not seeing any concurrency issues in modifying the state via player interaction (while generations take place) because the bullet explosions are inserted very quickly... but I'm not really sure. 

In theory is seems like there should be some issues I'm not accounting for, but it _seems_ to work pretty well... at least for now.

**Comment by BrianErikson** [comment]
Huh! Indeed it is already concurrent. I guess we'll revisit this if the player has issues interacting with the grid in the future.
