### ISSUE TITLE
Auto-increment Build major:minor versions on compile

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#78]
I've been doing some more research on this (since I'm lazy and can't remember to manually increment) and it appears you can do it via Gradle by executing an [ANT task](http://stackoverflow.com/questions/3439876/use-ant-to-update-build-number-and-inject-into-source-code). It appears we need some sort of [ANT xml file to increment the numbers](http://stackoverflow.com/a/1452157). I'm still really hazy on the implementation but it seems to be possible.

**Comment by BrianErikson** [comment]
Using Gradle's integration with groovy [seems to](http://paweloczadly.github.io/dev/2014/09/23/groovy-reading-and-writing-to-properties-file/) [be viable](http://stackoverflow.com/a/20872275) as well.

**Comment by 7yl4r** [comment]
Gradle, Groovy, ANT... I feel so lost when I look at this. It seems like it should be a common task. While increment-on-compile might be helpful, I think what we'll really need is some script we can explicitly run to update the various version numbers spread throughout. I know we have at least:
- semantic version in CellRPG.java
- semantic version in .gradle
- android semantic version for display in store
- android numeric version

Maybe my approach to this is unusual though... it sure feels like I'm not following a typical versioning paradigm since I can't find an easy tool to help with it.
